namespace ErosScriptingEngine.Lexer
{
    public enum TokenType
    {
        Bool,
        String,
        Number,
        Null,
        On,
        Start,
        Print,
        EndOfFile,
        Colon,
        Identifier,
        Indentation,
        End,
        Update,
        Id,
        Self,
        Dot,
        Name,
        Minus,
        Plus,
        Star,
        Slash,
        Not,
        LeftParen,
        RightParen
    }
}