namespace ErosScriptingEngine.Lexer
{
    public enum TokenType
    {
        Bool,
        String,
        Number,
        Null,
        On,
        Start,
        Print,
        EndOfFile,
        Colon,
        Identifier,
        End,
        Update,
        Id,
        Self,
        Dot,
        Name,
        Minus,
        Plus,
        Star,
        Slash,
        Not,
        LeftParen,
        RightParen,
        Destroy,
        Position,
        Set,
        To,
        Vec3,
        Rotation,
        Comma,
        DeltaTime,
        Time
    }
}